#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Marcel Petrick <mail@marcelpetrick.it>
"""The quality gate. CI runs exactly this script, so the two cannot drift.

    python3 localPipeline.py            # the full offline gate
    python3 localPipeline.py --network  # ... plus one live request as a canary
    python3 localPipeline.py --browser  # ... plus a headless render of the viewer

Steps, all offline unless asked otherwise:

    1. byte-compile every Python file (syntax gate)
    2. run the unit test suite
    3. build the viewer payload from the synthetic fixtures, end to end through
       the real command line, and check the result loads back
    4. check web/app.js with `node --check` when node is available
    5. optional canary: fetch one timetable page and confirm the site still has
       the markup the crawler relies on
    6. optional: render web/index.html in headless Chromium and fail on any
       console error

Only stdlib is needed for steps 1, 3, 4 and 6; the unit tests need the pinned
requirements, the canary needs `requests`.
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
import tempfile
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parent
FIXTURE_RAW = ROOT / "tests" / "fixtures" / "raw"

PASS, FAIL, SKIP = "PASS", "FAIL", "SKIP"


def info(message: str) -> None:
    print(f"[INFO] {message}", flush=True)


def run(command: list, **kwargs) -> subprocess.CompletedProcess:
    printable = " ".join(str(part) for part in command)
    info(f"$ {printable}")
    return subprocess.run(command, cwd=ROOT, **kwargs)


# ---------------------------------------------------------------- the steps
def step_compile() -> tuple[str, str]:
    targets = ["run.py", "localPipeline.py", "crawler", "tests"]
    result = run([sys.executable, "-m", "compileall", "-q", *targets],
                 stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
    if result.returncode != 0:
        print(result.stdout)
        return FAIL, "a Python file does not compile"
    return PASS, f"{', '.join(targets)} compile cleanly"


def step_unit_tests() -> tuple[str, str]:
    result = run([sys.executable, "-m", "unittest", "discover",
                  "-s", "tests", "-t", "tests", "-v"],
                 stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
    print(result.stdout)
    if result.returncode != 0:
        return FAIL, "unit tests failed"
    ran = [line for line in result.stdout.splitlines() if line.startswith("Ran ")]
    return PASS, ran[0] if ran else "unit tests passed"


def step_end_to_end() -> tuple[str, str]:
    """Drive parse.py over the fixtures the way run.py drives it over real data."""
    with tempfile.TemporaryDirectory() as tmp:
        json_path = Path(tmp) / "congress.json"
        web_path = Path(tmp) / "data.js"
        result = run([sys.executable, str(ROOT / "crawler" / "parse.py"),
                      "--raw-dir", str(FIXTURE_RAW),
                      "--json", str(json_path), "--web-data", str(web_path)],
                     stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
        print(result.stdout)
        if result.returncode != 0:
            return FAIL, "parse.py failed on the fixtures"
        if not json_path.exists() or not web_path.exists():
            return FAIL, "parse.py did not write both outputs"

        data = json.loads(json_path.read_text(encoding="utf-8"))
        payload = web_path.read_text(encoding="utf-8")
        if not payload.startswith("// Generated by"):
            return FAIL, "data.js lost its generated-file header"
        inline = payload.split("window.CONGRESS_DATA = ", 1)[1].rstrip().rstrip(";")
        if json.loads(inline)["events"] != data["events"]:
            return FAIL, "data.js and congress.json disagree"

        tagged = sum(1 for event in data["events"] if event["tags"])
        return PASS, (f"{len(data['days'])} day, {len(data['events'])} events, "
                      f"{tagged} tagged, both outputs reload")


def step_node_check() -> tuple[str, str]:
    node = shutil.which("node")
    if not node:
        return SKIP, "node not installed -- app.js not syntax checked"
    result = run([node, "--check", str(ROOT / "web" / "app.js")],
                 stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
    if result.returncode != 0:
        print(result.stdout)
        return FAIL, "web/app.js has a syntax error"
    return PASS, "web/app.js parses"


def step_network_canary() -> tuple[str, str]:
    """One request. Confirms the pages still carry the markup the crawler needs."""
    try:
        import requests
    except ImportError:
        return SKIP, "requests not installed"

    url = ("https://ese-kongress.de/frontend/index.php"
           "?page_id=53095&v=TimeTable&do=0&day=6480")
    info(f"GET {url}")
    try:
        response = requests.get(url, timeout=30, headers={"User-Agent": "localPipeline/1.0"})
        response.raise_for_status()
    except Exception as error:  # noqa: BLE001 - any failure is the same answer here
        return FAIL, f"could not reach the schedule: {error}"

    response.encoding = "utf-8"
    markers = ['class="event', "room_nav", "stepper-label", "v=List&amp;do=15", "topic_checkbox"]
    missing = [marker for marker in markers if marker not in response.text]
    if missing:
        return FAIL, f"page structure changed, missing: {', '.join(missing)}"
    return PASS, f"live page still carries all {len(markers)} markers the parser uses"


def step_browser() -> tuple[str, str]:
    """Render the built viewer headlessly and fail on a console error."""
    viewer = ROOT / "web" / "index.html"
    data = ROOT / "web" / "data.js"
    if not data.exists():
        return SKIP, "web/data.js not built -- run run.py first"

    browser = next((shutil.which(name) for name in
                    ("chromium", "chromium-browser", "google-chrome-stable", "google-chrome")
                    if shutil.which(name)), None)
    if not browser:
        return SKIP, "no Chromium found"

    with tempfile.TemporaryDirectory() as tmp:
        shot = Path(tmp) / "viewer.png"
        result = run([browser, "--headless", "--disable-gpu", "--no-sandbox",
                      "--virtual-time-budget=8000", f"--screenshot={shot}",
                      "--window-size=1600,1000", "--enable-logging=stderr", "--v=0",
                      viewer.as_uri()],
                     stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
        errors = [line for line in result.stdout.splitlines()
                  if "Uncaught" in line or "CONSOLE:" in line and "ERROR" in line]
        if errors:
            print("\n".join(errors[:5]))
            return FAIL, "the viewer logged an error"
        if not shot.exists():
            return FAIL, "the browser produced no screenshot"
        return PASS, f"viewer rendered ({shot.stat().st_size // 1024} KB screenshot)"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--network", action="store_true",
                        help="also send one live request to the congress site")
    parser.add_argument("--browser", action="store_true",
                        help="also render web/index.html in headless Chromium")
    args = parser.parse_args()

    steps = [
        ("Compile", step_compile),
        ("Unit tests", step_unit_tests),
        ("Fixture build", step_end_to_end),
        ("app.js syntax", step_node_check),
    ]
    if args.network:
        steps.append(("Live canary", step_network_canary))
    if args.browser:
        steps.append(("Viewer render", step_browser))

    info(f"Project root: {ROOT}")
    info(f"Interpreter : {sys.executable} ({sys.version.split()[0]})")

    started = time.monotonic()
    results = []
    for name, function in steps:
        info(f"--- {name} ---")
        try:
            status, detail = function()
        except Exception as error:  # noqa: BLE001 - a crashing step is a failing step
            status, detail = FAIL, f"step raised {type(error).__name__}: {error}"
        results.append((name, status, detail))

    width = max(len(name) for name, _, _ in results)
    print("\n========== Local Pipeline Summary ==========")
    for name, status, detail in results:
        print(f"{name:<{width}} : {status} {detail}")
    print("============================================")
    print(f"took {time.monotonic() - started:.1f}s")

    failed = [name for name, status, _ in results if status == FAIL]
    if failed:
        print(f"\nFAILED: {', '.join(failed)}")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
